version: "3"

services:
  fmaster:
    image:  flink:1.10.0
    ports:
      - "6123:6123"
      - "6124:6124"
      - "6125:6125"
      - "8081:8081"
    command: jobmanager
    volumes:
      - ./conf:/opt/flink/conf
      - ./etc/hostname:/etc/hostname
      - ./etc/hosts:/etc/hosts
      - ./.ssh:/root/.ssh
    environment:
      - JOB_MANAGER_RPC_ADDRESS=fmaster
