version: "3"

services:
  fmaster:
    image: flink:scala_2.12
    ports:
      - "6123:6123"
      - "8081:8081"
    command: jobmanager
    volumes:
      - ./conf:/opt/flink/conf
      - ./etc/hostname:/etc/hostname
      - ./etc/hosts:/etc/hosts
    environment:
      - JOB_MANAGER_RPC_ADDRESS=fmaster
