version: "3"

services:
  fmaster:
    image: flink:1.9.2-scala_2.11
    ports:
      - "6123:6123"
      - "8081:8081"
    command: jobmanager
    volumes:
      - ./conf:/opt/flink/conf
    environment:
      - JOB_MANAGER_RPC_ADDRESS=fmaster
