version: '2'

networks: 
  rcas: 
    external: true

services:
  zookeeper:
    image: 'bitnami/zookeeper:3.5.7'
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks: 
      - rcas
  kafka1:
    image: 'bitnami/kafka:2.4.0-ol-7-r55'
    hostname: kafka1
    container_name: kafka1
    ports:
      - '9092'
      - '19092:19092'
    depends_on: 
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:19092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka1:9092,EXTERNAL://${HOST}:19092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    networks: 
      - rcas
  kafka2:
    image: 'bitnami/kafka:2.4.0-ol-7-r55'
    hostname: kafka2
    container_name: kafka2
    ports:
      - '9092'
      - '29092:29092'
    depends_on: 
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=2
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka2:9092,EXTERNAL://${HOST}:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    networks: 
      - rcas
  kafka3:
    image: 'bitnami/kafka:2.4.0-ol-7-r55'
    hostname: kafka3
    container_name: kafka3
    ports:
      - '9092'
      - '39092:39092'
    depends_on: 
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=3
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:39092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka3:9092,EXTERNAL://${HOST}:39092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    networks: 
      - rcas
  kafka4:
    image: 'bitnami/kafka:2.4.0-ol-7-r55'
    hostname: kafka4
    container_name: kafka4
    ports:
      - '9092'
      - '49092:49092'
    depends_on: 
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=4
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:49092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka4:9092,EXTERNAL://${HOST}:49092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    networks: 
      - rcas
  kafka5:
    image: 'bitnami/kafka:2.4.0-ol-7-r55'
    hostname: kafka5
    container_name: kafka5
    ports:
      - '9092'
      - '59092:59092'
    depends_on: 
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=5
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:59092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka5:9092,EXTERNAL://${HOST}:59092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    networks: 
      - rcas
  kafka6:
    image: 'bitnami/kafka:2.4.0-ol-7-r55'
    hostname: kafka6
    container_name: kafka6
    ports:
      - '9092'
      - '6906:6906'
    depends_on: 
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=6
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:6906
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka6:9092,EXTERNAL://${HOST}:6906
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    networks: 
      - rcas
  kafka7:
    image: 'bitnami/kafka:2.4.0-ol-7-r55'
    hostname: kafka7
    container_name: kafka7
    ports:
      - '9092'
      - '7907:7907'
    depends_on: 
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=7
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:7907
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka7:9092,EXTERNAL://${HOST}:7907
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    networks: 
      - rcas
  kafka8:
    image: 'bitnami/kafka:2.4.0-ol-7-r55'
    hostname: kafka8
    container_name: kafka8
    ports:
      - '9092'
      - '8908:8908'
    depends_on: 
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=8
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:8908
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka8:9092,EXTERNAL://${HOST}:8908
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    networks: 
      - rcas